/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Thinkpad
 */
public class popup extends javax.swing.JDialog {

  /**
   * Creates new form popup
   */
  public popup(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    innit();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
   * Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    pnlDMK = new javax.swing.JPanel();
    txtDMK = new javax.swing.JLabel();
    pnlDTT = new javax.swing.JPanel();
    txtDTT = new javax.swing.JLabel();
    pnlHuy = new javax.swing.JPanel();
    txtHuy = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setUndecorated(true);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

    pnlDMK.setBackground(new java.awt.Color(255, 255, 255));
    pnlDMK.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        pnlDMKMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        pnlDMKMouseExited(evt);
      }
    });
    pnlDMK.setLayout(new java.awt.CardLayout());

    txtDMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtDMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtDMK.setText("Đổi mật khẩu");
    pnlDMK.add(txtDMK, "card2");

    pnlDTT.setBackground(new java.awt.Color(255, 255, 255));
    pnlDTT.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        pnlDTTMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        pnlDTTMouseExited(evt);
      }
    });
    pnlDTT.setLayout(new java.awt.CardLayout());

    txtDTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtDTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtDTT.setText("Xem thông tin cá nhân");
    pnlDTT.add(txtDTT, "card2");

    pnlHuy.setBackground(new java.awt.Color(255, 255, 255));
    pnlHuy.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        pnlHuyMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        pnlHuyMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        pnlHuyMouseExited(evt);
      }
    });
    pnlHuy.setLayout(new java.awt.CardLayout());

    txtHuy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtHuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtHuy.setText("Huỷ");
    pnlHuy.add(txtHuy, "card2");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlDMK, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addComponent(pnlDTT, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addComponent(pnlHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(pnlDMK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(pnlDTT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(pnlHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void pnlDMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDMKMouseEntered
    // TODO add your handling code here:
    setColor(pnlDMK, txtDMK);
  }//GEN-LAST:event_pnlDMKMouseEntered

  private void pnlDMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDMKMouseExited
    // TODO add your handling code here:
    resetColor(pnlDMK, txtDMK);
  }//GEN-LAST:event_pnlDMKMouseExited

  private void pnlDTTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDTTMouseEntered
    // TODO add your handling code here:
    setColor(pnlDTT, txtDTT);
  }//GEN-LAST:event_pnlDTTMouseEntered

  private void pnlDTTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDTTMouseExited
    // TODO add your handling code here:
    resetColor(pnlDTT, txtDTT);
  }//GEN-LAST:event_pnlDTTMouseExited

  private void pnlHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuyMouseEntered
    // TODO add your handling code here:
    setColor(pnlHuy, txtHuy);
  }//GEN-LAST:event_pnlHuyMouseEntered

  private void pnlHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuyMouseExited
    // TODO add your handling code here:
    resetColor(pnlHuy, txtHuy);
  }//GEN-LAST:event_pnlHuyMouseExited

  private void pnlHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuyMouseClicked
    // TODO add your handling code here:
    this.setVisible(false);
  }//GEN-LAST:event_pnlHuyMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        popup dialog = new popup(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel pnlDMK;
  private javax.swing.JPanel pnlDTT;
  private javax.swing.JPanel pnlHuy;
  private javax.swing.JLabel txtDMK;
  private javax.swing.JLabel txtDTT;
  private javax.swing.JLabel txtHuy;
  // End of variables declaration//GEN-END:variables

  void innit() {
    this.setLocationRelativeTo(null);
  }
  
  void setColor(JPanel pane, JLabel field) {
    pane.setBackground(new Color(99, 184, 255));
    field.setForeground(Color.white);
  }
  
  void resetColor(JPanel pane, JLabel field) {
    pane.setBackground(Color.white);
    field.setForeground(Color.black);
  }
}
