/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Thinkpad
 */
public class popup extends javax.swing.JDialog {
  
  int check;

  /**
   * Creates new form popup
   */
  public popup(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    init();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
   * Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    pnlDMK = new javax.swing.JPanel();
    txtDMK = new javax.swing.JLabel();
    pnlQLNV = new javax.swing.JPanel();
    txtDTT = new javax.swing.JLabel();
    pnlDangXuat = new javax.swing.JPanel();
    txtDangXuat = new javax.swing.JLabel();
    pnlHuy = new javax.swing.JPanel();
    txtHuy = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setUndecorated(true);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
    jPanel1.setLayout(new java.awt.GridLayout(4, 1));

    pnlDMK.setBackground(new java.awt.Color(255, 255, 255));
    pnlDMK.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        pnlDMKMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        pnlDMKMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        pnlDMKMouseExited(evt);
      }
    });
    pnlDMK.setLayout(new java.awt.CardLayout());

    txtDMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtDMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtDMK.setText("Đổi mật khẩu");
    pnlDMK.add(txtDMK, "card2");

    jPanel1.add(pnlDMK);

    pnlQLNV.setBackground(new java.awt.Color(255, 255, 255));
    pnlQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        pnlQLNVMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        pnlQLNVMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        pnlQLNVMouseExited(evt);
      }
    });
    pnlQLNV.setLayout(new java.awt.CardLayout());

    txtDTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtDTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtDTT.setText("Quản lý nhân viên");
    pnlQLNV.add(txtDTT, "card2");

    jPanel1.add(pnlQLNV);

    pnlDangXuat.setBackground(new java.awt.Color(255, 255, 255));
    pnlDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        pnlDangXuatMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        pnlDangXuatMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        pnlDangXuatMouseExited(evt);
      }
    });
    pnlDangXuat.setLayout(new java.awt.CardLayout());

    txtDangXuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtDangXuat.setText("Đăng xuất");
    pnlDangXuat.add(txtDangXuat, "card2");

    jPanel1.add(pnlDangXuat);

    pnlHuy.setBackground(new java.awt.Color(255, 255, 255));
    pnlHuy.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        pnlHuyMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        pnlHuyMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        pnlHuyMouseExited(evt);
      }
    });
    pnlHuy.setLayout(new java.awt.CardLayout());

    txtHuy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtHuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtHuy.setText("Huỷ");
    pnlHuy.add(txtHuy, "card2");

    jPanel1.add(pnlHuy);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void pnlDMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDMKMouseEntered
    // TODO add your handling code here:
    setColor(pnlDMK, txtDMK);
  }//GEN-LAST:event_pnlDMKMouseEntered

  private void pnlDMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDMKMouseExited
    // TODO add your handling code here:
    resetColor(pnlDMK, txtDMK);
  }//GEN-LAST:event_pnlDMKMouseExited

  private void pnlQLNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLNVMouseEntered
    // TODO add your handling code here:
    setColor(pnlQLNV, txtDTT);
  }//GEN-LAST:event_pnlQLNVMouseEntered

  private void pnlQLNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLNVMouseExited
    // TODO add your handling code here:
    resetColor(pnlQLNV, txtDTT);
  }//GEN-LAST:event_pnlQLNVMouseExited

  private void pnlHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuyMouseEntered
    // TODO add your handling code here:
    setColor(pnlHuy, txtHuy);
  }//GEN-LAST:event_pnlHuyMouseEntered

  private void pnlHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuyMouseExited
    // TODO add your handling code here:
    resetColor(pnlHuy, txtHuy);
  }//GEN-LAST:event_pnlHuyMouseExited

  private void pnlDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDangXuatMouseEntered
    // TODO add your handling code here:
    setColor(pnlDangXuat, txtDangXuat);
  }//GEN-LAST:event_pnlDangXuatMouseEntered

  private void pnlDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDangXuatMouseExited
    // TODO add your handling code here:
    resetColor(pnlDangXuat, txtDangXuat);
  }//GEN-LAST:event_pnlDangXuatMouseExited

  private void pnlHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuyMouseClicked
    // TODO add your handling code here:
    setVisible(false);
  }//GEN-LAST:event_pnlHuyMouseClicked

  private void pnlDMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDMKMouseClicked
    // TODO add your handling code here:
    TrangChuFrame.popup = 1;
    setVisible(false);
  }//GEN-LAST:event_pnlDMKMouseClicked

  private void pnlQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLNVMouseClicked
    // TODO add your handling code here:
    TrangChuFrame.popup = 2;
    setVisible(false);
  }//GEN-LAST:event_pnlQLNVMouseClicked

  private void pnlDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDangXuatMouseClicked
    // TODO add your handling code here:
    TrangChuFrame.popup = 3;    
    setVisible(false);
  }//GEN-LAST:event_pnlDangXuatMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        popup dialog = new popup(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel pnlDMK;
  private javax.swing.JPanel pnlDangXuat;
  private javax.swing.JPanel pnlHuy;
  private javax.swing.JPanel pnlQLNV;
  private javax.swing.JLabel txtDMK;
  private javax.swing.JLabel txtDTT;
  private javax.swing.JLabel txtDangXuat;
  private javax.swing.JLabel txtHuy;
  // End of variables declaration//GEN-END:variables

  void init() {
    this.setLocationRelativeTo(null);
    pnlQLNV.setVisible(false);
  }
  
  void setColor(JPanel pane, JLabel field) {
    pane.setBackground(new Color(99, 184, 255));
    field.setForeground(Color.white);
  }
  
  void resetColor(JPanel pane, JLabel field) {
    pane.setBackground(Color.white);
    field.setForeground(Color.black);
  }
}
