/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Thinkpad
 */
public class TrangChuFrame extends javax.swing.JFrame {

  /**
   * Creates new form TrangChuFrame
   */
  public TrangChuFrame() {
    initComponents();
    innit();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
   * Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    lblUser = new javax.swing.JLabel();
    pnlCaiDat = new javax.swing.JPanel();
    txtCD = new javax.swing.JLabel();
    pnlThongKe = new javax.swing.JPanel();
    txtTK = new javax.swing.JLabel();
    pnlQuanLy = new javax.swing.JPanel();
    txtQL = new javax.swing.JLabel();
    pnlTrangChu = new javax.swing.JPanel();
    txtTC = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    exit = new javax.swing.JLabel();
    minimize = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("TRANG CHỦ");
    setUndecorated(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));

    lblUser.setBackground(new java.awt.Color(0, 102, 102));
    lblUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lblUser.setForeground(new java.awt.Color(0, 102, 102));
    lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/manager.png"))); // NOI18N
    lblUser.setText("Thanh Lam");
    lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lblUserMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 90));

    pnlCaiDat.setBackground(new java.awt.Color(255, 255, 255));
    pnlCaiDat.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        pnlCaiDatMousePressed(evt);
      }
    });
    pnlCaiDat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtCD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    txtCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtCD.setText("Cài đặt");
    pnlCaiDat.add(txtCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 12, 82, -1));

    jPanel1.add(pnlCaiDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 240, 50));

    pnlThongKe.setBackground(new java.awt.Color(255, 255, 255));
    pnlThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        pnlThongKeMousePressed(evt);
      }
    });
    pnlThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtTK.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    txtTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtTK.setText("Thống kê");
    pnlThongKe.add(txtTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 12, 82, -1));

    jPanel1.add(pnlThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 50));

    pnlQuanLy.setBackground(new java.awt.Color(255, 255, 255));
    pnlQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        pnlQuanLyMousePressed(evt);
      }
    });
    pnlQuanLy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtQL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    txtQL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtQL.setText("Quản lý");
    pnlQuanLy.add(txtQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 12, 82, -1));

    jPanel1.add(pnlQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 50));

    pnlTrangChu.setBackground(new java.awt.Color(255, 255, 255));
    pnlTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        pnlTrangChuMousePressed(evt);
      }
    });
    pnlTrangChu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtTC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    txtTC.setText("Trang chủ");
    pnlTrangChu.add(txtTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 12, -1, -1));

    jPanel1.add(pnlTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 188, 240, 50));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 240, 750));

    jPanel2.setBackground(new java.awt.Color(204, 204, 204));
    jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
      public void mouseDragged(java.awt.event.MouseEvent evt) {
        jPanel2MouseDragged(evt);
      }
    });
    jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        jPanel2MousePressed(evt);
      }
    });

    jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fav.png"))); // NOI18N
    jLabel7.setText("Quản lý shop thú cưng");

    exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N
    exit.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        exitMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        exitMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        exitMouseExited(evt);
      }
    });

    minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/minimize.png"))); // NOI18N
    minimize.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        minimizeMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        minimizeMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        minimizeMouseExited(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 922, Short.MAX_VALUE)
        .addComponent(minimize)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(exit)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(exit)
          .addComponent(minimize)
          .addComponent(jLabel7))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 20));

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BG.png"))); // NOI18N
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1160, 750));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void pnlTrangChuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTrangChuMousePressed
    // TODO add your handling code here:
    resetColor();
    setColor(pnlTrangChu);
    txtTC.setForeground(Color.white);
  }//GEN-LAST:event_pnlTrangChuMousePressed

  private void pnlQuanLyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuanLyMousePressed
    // TODO add your handling code here:
    resetColor();
    setColor(pnlQuanLy);
    txtQL.setForeground(Color.white);
  }//GEN-LAST:event_pnlQuanLyMousePressed

  private void pnlThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMousePressed
    // TODO add your handling code here:
    resetColor();
    setColor(pnlThongKe);
    txtTK.setForeground(Color.white);
  }//GEN-LAST:event_pnlThongKeMousePressed

  private void pnlCaiDatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCaiDatMousePressed
    // TODO add your handling code here:
    resetColor();
    setColor(pnlCaiDat);
    txtCD.setForeground(Color.white);
  }//GEN-LAST:event_pnlCaiDatMousePressed

  private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
    // TODO add your handling code here:
    popup popup = new popup(this, true);
    popup.setVisible(true);
  }//GEN-LAST:event_lblUserMouseClicked

  private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_exitMouseClicked

  private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
    // TODO add your handling code here:
    exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit-20.png")));
  }//GEN-LAST:event_exitMouseEntered

  private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
    // TODO add your handling code here:
    exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png")));
  }//GEN-LAST:event_exitMouseExited

  private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
    // TODO add your handling code here:
    this.setState(1);
  }//GEN-LAST:event_minimizeMouseClicked

  private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
    // TODO add your handling code here:
    minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/minimize-20.png")));
  }//GEN-LAST:event_minimizeMouseEntered

  private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
    // TODO add your handling code here:
    minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/minimize.png")));
  }//GEN-LAST:event_minimizeMouseExited

  int xx,xy;
  private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
    // TODO add your handling code here:
    xx = evt.getX();
    xy = evt.getY();
  }//GEN-LAST:event_jPanel2MousePressed

  private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
    // TODO add your handling code here:
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen();
    this.setLocation(x-xx,y-xy);
  }//GEN-LAST:event_jPanel2MouseDragged

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TrangChuFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel exit;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JLabel lblUser;
  private javax.swing.JLabel minimize;
  private javax.swing.JPanel pnlCaiDat;
  private javax.swing.JPanel pnlQuanLy;
  private javax.swing.JPanel pnlThongKe;
  private javax.swing.JPanel pnlTrangChu;
  private javax.swing.JLabel txtCD;
  private javax.swing.JLabel txtQL;
  private javax.swing.JLabel txtTC;
  private javax.swing.JLabel txtTK;
  // End of variables declaration//GEN-END:variables

void innit() {
    this.setLocationRelativeTo(null);
    URL path = TrangChuFrame.class.getResource("/Image/fav.png");
    this.setIconImage(new ImageIcon(path).getImage());
  }

  void setColor(JPanel pane) {
    pane.setBackground(new Color(99, 184, 255));    
  }
  
  void resetColor() {
    pnlTrangChu.setBackground(Color.white);
    pnlQuanLy.setBackground(Color.white);
    pnlThongKe.setBackground(Color.white);
    pnlCaiDat.setBackground(Color.white);
    txtTC.setForeground(Color.black);
    txtQL.setForeground(Color.black);
    txtTK.setForeground(Color.black);
    txtCD.setForeground(Color.black);
  }

}
